### ISSUE TITLE
NFR: The tool will have a pre-set limit on users and data volumes enabled and supported for free in the cloud version, and free enablement/support will be for a prescribed period of time.

### ISSUE THREAD

**Issue by sreyac** [CriticalAssetManagement/CAMS#112]
We need to specify limits.

**Comment by rpwilliams1958** [comment]
For Terminus DB to decide first - how much data can you host without breaking your company?!  I believe we discussed this previously but I cannot recall the numbers we decided.  Dominica may have about 500 assets by the time they are done.  What's the data volume per asset?
