### ISSUE TITLE
Unable to edit existing assets: Asset history, asset update history,  applicable events

### ISSUE THREAD

**Issue by OJ423** [CriticalAssetManagement/CAMS#155]
A user cannot update existing assets to add new applicable events, asset history or to update asset history. The three buttons are unresponsive and do nothing upon clicking. 

![image](https://user-images.githubusercontent.com/88653154/167372836-21f137bf-e13e-43b0-8ae4-d54e7052290d.png)

**Comment by KittyJose** [comment]
@OJ423 can you try this again? there was an issue with version of terminusdb-documents-ui in CAMS and thats what caused these issues. I can confirm that when I tested this issue, it worked fine for me. We could close this issue once your happy with it 👯

**Comment by OJ423** [comment]
Hi @KittyJose, I'm still unable to edit them, the buttons are still unresponsive for me.

**Comment by KittyJose** [comment]
Hey @OJ423 are you using the correct URL ? 
```https://dashboard-dev.climateresilient.world```

**Comment by OJ423** [comment]
All fixed.
