### ISSUE TITLE
Emergency Response: Generate context-aware action recommendations either on a rules basis, or (preferably) using AI to generate recommendations.

### ISSUE THREAD

**Issue by sreyac** [CriticalAssetManagement/CAMS#90]
Enable a library of SOPs relating to each asset, so stakeholders can understand how different assets will be affected by a disaster and how the asset owners will respond. (_**creation and assembly of SOPs is not in scope**_)

**Comment by rpwilliams1958** [comment]
Phase 2?  I'd be inclined to see if the global user community can address this - once it has formed...
